// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-01-21 10:49:40.303623 -0800 PST m=+0.015639194
package cmd

const GITVERSION = `0386bfa initial commit`
const SEMVER = "0.0.0a"
const GLIDEDEPS = ``
