// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-05-18 11:17:47.19347 -0400 EDT m=+0.031431156
package cmd

const GITVERSION = `60adae8 update apns code to toggle off wiht no key`
const SEMVER = "2.0.0"
const DEPENDENCIES = `module git.xx.network/elixxir/notifications-bot

go 1.13

require (
	cloud.google.com/go v0.55.0 // indirect
	cloud.google.com/go/firestore v1.1.1 // indirect
	cloud.google.com/go/pubsub v1.3.1 // indirect
	firebase.google.com/go v3.12.0+incompatible
	github.com/golang/protobuf v1.4.3 // indirect
	github.com/jonahh-yeti/apns v0.0.1
	github.com/mitchellh/go-homedir v1.1.0
	github.com/pkg/errors v0.9.1
	github.com/spf13/cobra v1.0.0
	github.com/spf13/jwalterweatherman v1.1.0

	github.com/spf13/viper v1.7.0
	git.xx.network/elixxir/comms v0.0.4-0.20210517210053-819dc80aa1c9
	git.xx.network/elixxir/crypto v0.0.7-0.20210517205836-5930e34ed931
	git.xx.network/xx_network/comms v0.0.4-0.20210517205649-06ddfa8d2a75
	git.xx.network/xx_network/crypto v0.0.5-0.20210517205543-4ae99cbb9063
	git.xx.network/xx_network/primitives v0.0.4-0.20210517202253-c7b4bd0087ea
	golang.org/x/net v0.0.0-20210510120150-4163338589ed
	golang.org/x/tools v0.0.0-20200318150045-ba25ddc85566 // indirect
	google.golang.org/api v0.20.0
	google.golang.org/genproto v0.0.0-20201030142918-24207fddd1c3 // indirect
	google.golang.org/grpc v1.33.1 // indirect
	gopkg.in/ini.v1 v1.56.0 // indirect
	gorm.io/driver/postgres v1.0.8
	gorm.io/gorm v1.20.12
)
`
